@BASE_URL = http://localhost:3022

### GET ADOPTANTE BY ID_ADOPTANTE
GET {{BASE_URL}}/adoptantes/61 HTTP/1.1
Content-Type: application/json

### GET ADOPTANTES
GET {{BASE_URL}}/adoptantes HTTP/1.1
Content-Type: application/json

### UPDATE ADOPTANTE BY ID
PUT {{BASE_URL}}/adoptantes/6 HTTP/1.1
Content-Type: application/json

{
    "nombres": "Juan",
    "apellido": "Perez",
    "telefono": "12345678"
    
}

### DELETE ADOPTANTE BY ID
DELETE {{BASE_URL}}/adoptantes/6 HTTP/1.1

### CREATE ADOPTANTE
POST {{BASE_URL}}/adoptantes HTTP/1.1
Content-Type: application/json

{
    "nombres": "Juan",
    "apellido": "Perez",
    "telefono": "12345678",
    "id_adoptante" : "56",
    "fecha" : "2013-08-28",
    "observaciones" : "Fallecido"

}
  