@BASE_URL = http://localhost:3022

### CREATE CAT
POST {{BASE_URL}}/felinos HTTP/1.1
Content-Type: application/json

{
    "ingreso": "2024-03-09",
    "nombre": "Felino Backend",
    "hc": 2727
}  

### GET ALL CATS
GET {{BASE_URL}}/felinos HTTP/1.1
Content-Type: application/json

### GET CAN BY ID
GET {{BASE_URL}}/felinos/1 HTTP/1.1
Content-Type: application/json

### UPDATE CAN
PUT {{BASE_URL}}/felinos/1 HTTP/1.1
Content-Type: application/json

{
    "ingreso": "2024-03-09",
    "nombre": "Felino Backend Editado",
    "hc": 2722
}

### GET ESTADOS Y RAZAS
GET {{BASE_URL}}/felinos-razas-estados HTTP/1.1
Content-Type: application/json

### CREATE FOTO CAN
POST {{BASE_URL}}/felinos/fotos HTTP/1.1
Content-Type: application/json

{
    "id_gato_foto": 1,
    "detalle" : "Portada",
    "foto": "Pepe.jpg"
}

### GET FOTOS CAT
GET {{BASE_URL}}/felinos/fotos/1 HTTP/1.1
Content-Type: application/json

### DELETE FOTO CAT
DELETE {{BASE_URL}}/felinos/fotos HTTP/1.1
Content-Type: application/json

{
    "id_foto": 1
}

### GET FELINOS TRATAMIENTOS BY ID
GET {{BASE_URL}}/felinos/tratamientos/1 HTTP/1.1
Content-Type: application/json

### PUT FELINOS TRATAMIENTOS BY ID
PUT {{BASE_URL}}/felinos/tratamientos/1 HTTP/1.1
Content-Type: application/json

{
    "id_gato": 1,
    "tratamientos": "Editado desde el Backend"
}

### CREATE FELINOS RAZAS
POST {{BASE_URL}}/felinos/razas HTTP/1.1
Content-Type: application/json

{
    "nombre": "Persa"
} 

