@BASE_URL = http://localhost:3022

### Get Equinos Juidicializados
GET {{BASE_URL}}/judicial HTTP/1.1
Content-Type: application/json

### Get Equinos No Juidicializados
GET {{BASE_URL}}/no_judicial HTTP/1.1
Content-Type: application/json

### Get Equinos Judicializado By Id
GET {{BASE_URL}}/judicial/447 HTTP/1.1
Content-Type: application/json

### Create Judicial 
POST  {{BASE_URL}}/judicial
Content-Type: application/json

{
"id_caballo_judicial" : "447",
"fecha" : "2024-05-23",
"causa" : "07-00-12345-24", 
"ufi" : "1", 
"garantias" : "2",  
"juzgado" : "3",
"entrega" : "D. Judicial",
"diligencias" : "Diligencias"
}

### Update Judicial 
PUT  {{BASE_URL}}/judicial
Content-Type: application/json

{
"id_caballo_judicial" : "447",
"fecha" : "2024-05-23",
"causa" : "07-00-12345-24", 
"ufi" : "10", 
"garantias" : "20",  
"juzgado" : "30",
"entrega" : "D. Judicial",
"diligencias" : "Diligencias - Modificado"
}