@BASE_URL = http://localhost:3022

### GET ALL PEQUES
GET {{BASE_URL}}/peques HTTP/1.1

### GET PEQUE OPCIONES
GET {{BASE_URL}}/peques_opciones HTTP/1.1

### GET PEQUE BY ESPECIES
POST {{BASE_URL}}/peques HTTP/1.1
Content-Type: application/json

{
    "especie": "Felina"
}

### GET PEQUE BY ESTADO AND ESPECIE
POST {{BASE_URL}}/peques_estados_especies HTTP/1.1
Content-Type: application/json

{
    "estado": "2",
    "especie" : "Canina"
}

### GET PEQUE BY ESTADO  
POST {{BASE_URL}}/peques_estados HTTP/1.1
Content-Type: application/json

{
    "estado": "2"
}

### GET PEQUE BY ID
GET {{BASE_URL}}/peques/1 HTTP/1.1

### PUT PEQUE BY ID
PUT {{BASE_URL}}/peques/1 HTTP/1.1
Content-Type: application/json

{
    "nombre" : "Juanitaaaa",
    "edad" : 17
}